# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3b4214f1d628da0a53567f4ddafd786645a1bfc5d13d221cb26af6f15f33fd1afaccde07cf7df71cfe0c792c5b110ad22bc548bebfd087b8dcc06a97df0aa9d4

test:
  secret_key_base: 10a6d969c8694a6f6e9d696438bdd3bf299bf75865204dd633447a9cb60406159622c9bb2457b6f1d8f868ee7f5219d9b0eaf4cce1d643fa58c02093cf400b08

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
